### ISSUE TITLE
Very useful library., is there something similar (declarative) for json to extract data ?

### ISSUE THREAD

**Issue by tinkerbotfoo** [spurin/xmldataset#11]
This library is very easy & convenient to extract data from xml files. Is there similar library / functionality available for json ?

**Comment by spurin** [comment]
Thanks

Glad to hear you're getting good use from it, where did you hear about it by the way?

With regards to your question, not that I'm aware of but, it should be possible to do a similar utility with JSON :-)  I originally wrote this for Perl and then transitioned to Python.  It was a lot easier and cleaner owing to ElementTree being a core library and it having all of the necessary hooks when traversing the xml structure in a streaming fashion, i.e. root, element, attribute etc.  Could be an interesting project.

**Comment by tinkerbotfoo** [comment]
drumroll ... https://github.com/vinta/awesome-python . Thanks for adding it. I go there these days to find something useful.

**Comment by tinkerbotfoo** [comment]
Yeah it's very interesting. I am up for giving it a shot .. would you have sometime to review and advice ?

**Comment by spurin** [comment]
Thanks for previous comments, closing issue
