### ISSUE TITLE
Reading output into a pandas dataframe

### ISSUE THREAD

**Issue by keluc** [spurin/xmldataset#2]
With the method [from_records]( http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_records.html) one can use pandas.
Such an example in the documentation seems useful.

```
result = xmldataset.parse_using_profile(xml, profile)
df = pd.DataFrame.from_records(result['...'])
```

**Comment by spurin** [comment]
Thanks keluc, great point.  I'll add this in.  Have you any further context of where you've used this in pandas that I can use in the example?

**Comment by keluc** [comment]
I used your base example with the list of colleagues to try xmldataset out and I asked myself if this would be easy to integrate with pandas, which was simple to do:
....
df = pd.DataFrame.from_records(result['colleagues'])

(ps. there is an open [pandas issue](https://github.com/pydata/pandas/issues/4734))

**Comment by spurin** [comment]
Marking this as enhancement given that it enhances the documentation, thanks Keluc

**Comment by spurin** [comment]
Added to 1.0.1
