### ISSUE TITLE
Needs refactoring

### ISSUE THREAD

**Issue by KleinerNull** [spurin/xmldataset#4]
I was bored and looked into your code. I think it is not a good idea to write the complete code into the `__init__.py`.

I'd say one can split the _XMLDataset and the parse_using_profile code into seperate sub modules. So it can be easier to extend and change the code in the future.

After you'll have commited your actual changes I would refacture it for you, just don't want to mess with the merging problems now.

**Comment by spurin** [comment]
Agreed, I'm looking into your existing merge requests and feedback on the other areas, after that it should be easier moving forward with other merge requests.  Closing this issue for now.
