### ISSUE TITLE
Identifier for unique datasets

### ISSUE THREAD

**Issue by KleinerNull** [spurin/xmldataset#6]
This would be an interesting idea, I have prepared a [demo notebook](https://github.com/KleinerNull/Notebooks/blob/master/XMLDatasetDemo.ipynb) with a nasty xml response to parse from amazon ;)

As you can see the dataset `fulfillment_order` is unique, but still it is saved in a list, just with one element. It would be nice if you can say with an identifier, that that dataset is unique and won't be stored in a list, instead in a normal dictionary.  

`UNIQUE_DATASET` is my proposal for a name for such a identifier.

Otherwise, the possibility to flatten all one-element lists in the output would be also interesting.

**Comment by spurin** [comment]
Would you provide me with me a mock output showing your vision for this, I think it could be a good enhancement

**Comment by spurin** [comment]
Thanks for previous comments, closing issue
